### PR TITLE
Added some more terms, fleshed out some definitions.

### PR DESCRIPTION
**Pull request by modalpdx**
Howdy,

I tried to sync up the repos before I started this effort but Github said we were in sync already. Hopefully this pull request won't cause any heartache!

As always, please let me know if there are issues with the request.

Thanks!

E.

### CODE REVIEW

**Comment by lyzadanger** [comment]
Hi @modalpdx ! Don't you worry, we'll get this figured out.

Because you are working with a _fork_ of this repository, you will from time to time need to pull from this (`lyzadanger/JSoT`) repository, which is the "upstream" repository from your fork. Simply doing a `git pull` from `origin` on your own `master` branch won't get the changes from this repository.

I can see that your fork doesn't yet have the commits from this weekend merged:

image

Here are some docs about how to sync from upstream:

https://help.github.com/articles/syncing-a-fork/

Totally happy to help walk you through this if you have any trouble!

**Comment by modalpdx** [comment]
Wow, talk about instruction failures...the first time I sync'd the repos I used the instructions listed here:

http://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381

That _appeared_ to work. I tried to run through them again before changing the README.md file today and nothing looked quite the same as in the instructions so I figured we were in sync. Yep, never assume. 

I'm throwing away those instructions. I like yours much, much better. :)

I have run through them and sync'd everything up, fixed merge conflicts, and pushed to my fork. If you want, I can kill this pull request and try to do another one, or at least I think I can kill it. Just let me know.

Thanks, and sorry 'bout this!

E.

**Comment by lyzadanger** [comment]
First: Please don't feel sorry! We all go through this! It's happened to me, for sure.

Why don't you go ahead and open a new PR? Potentially less confusing.

**Comment by modalpdx** [comment]
Will do.

**Pull request closed without merging**
